language: go

go:
  - 1.4.1

before_install:
  - sudo pip install codecov

install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golang/lint/golint

before_script:
  - go get ./...
  - go vet ./...
  - golint ./... | xargs -r false

script:
  - go test -v -coverprofile=coverage.txt -covermode=count

after_success:
  - codecov
